### PR TITLE
fix: validate tool args_schema before execution in native mode (#4495)

### LINKED ISSUE #4495: [BUG] Regression in CrewAI 1.9.3: custom BaseTool wrapper around BedrockKBRetrieverTool gets called without args (_run() missing query) and enters infinite tool-use loop
### Description

After upgrading CrewAI from 1.6.1 → 1.9.3, a custom tool wrapper around BedrockKBRetrieverTool no longer receives its required query argument. The tool call fails with:
	•	ParsedBedrockKBRetrieverTool._run() missing 1 required positional argument: 'query'
…and the agent repeatedly attempts to use the tool, effectively entering an infinite tool-calling loop.
In crewai==1.6.1, the same code and workflow work as expected.

The logs also show an events mismatch warning during the loop:
[CrewAIEventsBus] Warning: Event pairing mismatch. 'tool_usage_finished' closed 
'flow_started' (expected 'tool_usage_started')
Tool kb_retrieve executed with result: Error executing tool: ParsedBedrockKBRetrieverTool._run() missing 1 required positional argument: 'query'

This looks like a regression in how tool arguments are passed from the agent → tool execution in newer CrewAI versions.

Environment
	•	crewai==1.9.3 (broken)
	•	crewai==1.6.1 (works)
	•	Tool involved: crewai_tools.aws.bedrock.knowledge_base.retriever_tool.BedrockKBRetrieverTool  ￼
	•	Custom tool extends crewai.tools.BaseTool (wrapper with post-processing)

### Steps to Reproduce

1.	Install and run with crewai==1.9.3
	2.	Create an agent (in a Crew) that has a tool list including a custom wrapper tool around BedrockKBRetrieverTool.
	3.	Ask the agent a question that triggers retrieval from the knowledge base.
	4.	Observe that the tool fails with a missing query arg, and the agent repeatedly retries tool usage.

### Expected behavior

Expected behavior
	•	The tool should be invoked with the query argument (as defined by the tool schema), execute once, and return retrieval results (JSON).

Actual behavior
	•	Tool execution fails because _run() is called without the required query parameter.
	•	The agent loops, repeatedly trying to use the tool.
	•	Event bus warning appears: “Event pairing mismatch … expected tool_usage_started”.

### Screenshots/Code snippets

from typing import Type
import json
from pydantic import BaseModel, Field, PrivateAttr
from crewai.tools import BaseTool
from crewai_tools.aws.bedrock.knowledge_base.retriever_tool import BedrockKBRetrieverTool

class KBQueryInput(BaseModel):
    """Input schema for KB retrieval tool."""
    query: str = Field(..., description="Natural language query for the knowledge base.")

class ParsedBedrockKBRetrieverTool(BaseTool):
    name: str = "kb.retrieve"
    description: str = "Retrieve from Bedrock KB and parse results into RetrievedRef-shaped objects."
    args_schema: Type[BaseModel] = KBQueryInput
    _inner: BedrockKBRetrieverTool = PrivateAttr()

    def __init__(self, inner: BedrockKBRetrieverTool):
        super().__init__()
        self._inner = inner

    def _run(self, query: str) -> str:
        raw = self._inner._run(query)

        try:
            payload = json.loads(raw) if isinstance(raw, str) else raw
        except Exception:
            return json.dumps({"message": "Failed to parse BedrockKBRetrieverTool response as JSON."})

        if not isinstance(payload, dict):
            return json.dumps({"message": "Unexpected BedrockKBRetrieverTool response type."})

        results = payload.get("results")
        if results is None:
            return json.dumps({"message": payload.get("message", "No results found for the given query.")})

        # parsing logic omitted for brevity...
        return json.dumps({"results": results})

def build_kb_retrieval_tool(knowledge_base_id: str, n_results: int = 100) -> BaseTool:
    inner = BedrockKBRetrieverTool(
        knowledge_base_id=knowledge_base_id,
        number_of_results=n_results
    )
    return ParsedBedrockKBRetrieverTool(inner=inner)

### Operating System

Ubuntu 22.04

### Python Version

3.12

### crewAI Version

1.9.3

### crewAI Tools Version

1.9.3

### Virtual Environment

Poetry

### Evidence

[CrewAIEventsBus] Warning: Event pairing mismatch. 'tool_usage_finished' closed 
'flow_started' (expected 'tool_usage_started')
Tool kb_retrieve executed with result: Error executing tool: ParsedBedrockKBRetrieverTool._run() missing 1 required positional argument: 'query'...

### Possible Solution

None
in early version its works

### Additional context

None

### PR DESCRIPTION
**Pull request by amabito**
## Summary
Native tool calling mode bypasses `CrewStructuredTool.invoke()` / `_parse_args()` and calls `BaseTool.run()` directly via `available_functions`. When required arguments are missing, this produces a raw `TypeError` that can trigger deterministic retry loops.

## Fix
Validate `args_dict` against the matched tool's `args_schema` before execution in `_handle_native_tool_calls()`.

```python
if original_tool and getattr(original_tool, "args_schema", None):
    validated = original_tool.args_schema.model_validate(args_dict)
    args_dict = validated.model_dump()
```

Missing or invalid arguments now raise `ValidationError`, which is handled by the existing outer exception block.

Native mode now normalizes arguments via Pydantic (including filling schema defaults), which aligns behavior with the ReAct path.

## Scope
- Minimal change limited to native tool-calling path
- No changes to ReAct path
- No signature changes
- No new imports
- Backward compatible

## Tests
- Added regression tests covering missing required args
- Verified valid args still execute correctly

Closes #4495

---

> [!NOTE]
> **Low Risk**
> Small, localized change to the native tool execution path with added tests; main risk is minor behavior change in how invalid tool args are surfaced.
> 
> **Overview**
> Native tool calling now validates the parsed `args_dict` against the matched tool’s Pydantic `args_schema` before invoking the tool function, normalizing defaults and turning missing/invalid args into handled validation errors instead of raw `TypeError`s.
> 
> Adds regression tests that reproduce the missing-required-arg scenario in native mode (ensuring `_run` is not called and a validation-style error is returned) and a sanity check that valid arguments still execute successfully.
> 
> <sup>Written by [Cursor Bugbot](https://cursor.com/dashboard?tab=bugbot) for commit cc3ffb6b1ce1eef0c2324e297dec6ac9f68cc07e. This will update automatically on new commits. Configure [here](https://cursor.com/dashboard?tab=bugbot).</sup>

### CODE REVIEW

**Comment by amabito** [comment]
@jonas-cohen-verbit FYI — PR is up. If you can test this branch against your setup, that would be super helpful.

It validates `args_dict` against `args_schema` in native tool calling before executing `tool.run()`, which prevents missing-required-arg TypeErrors and aligns native behavior with the structured/ReAct path.

**Comment by amabito** [comment]
Closing this in favor of #4518, which fixes the actual root cause at L722.

The `args_dict` being empty was not due to missing validation, but because `func_info.get("arguments", "{}") or tool_call.get("input", {})` short-circuits on the truthy default `"{}"`, so Bedrock's `input` key is never evaluated. #4518 addresses that directly with a one-line fix.

The Pydantic validation approach in this PR (filling schema defaults, normalizing args) is a reasonable defensive improvement in its own right — happy to reopen or submit a separate PR for it if the team finds it useful.

Thanks for the patience while we narrowed down the root cause.
