### ISSUE TITLE
[BUG] ChromaDB adds dependencies which cannot be satisfied on Mac OS.

### ISSUE THREAD

**Issue by wanderingnature** [crewAIInc/crewAI#3202]
### Description

# CrewAI Dependency Conflicts Prevent Upgrades on macOS

## Problem Summary
CrewAI has dependency management issues that prevent users from upgrading to newer versions on macOS and create incompatibilities between core CrewAI and crewai-tools packages. This blocks adoption of new features and creates maintenance burden for production deployments.

### Description
CrewAI versions beyond v0.121.1 cannot be installed on macOS due to an impossible onnxruntime dependency requirement.

### Root Cause
- CrewAI v0.148.0 requires `onnxruntime==1.22.0` through ChromaDB dependency
- `onnxruntime==1.22.0` does not exist for macOS (only versions up to 1.19.2 are available)
- This creates an unsolvable dependency constraint

### Dependency Chain
```
CrewAI v0.148.0 → ChromaDB ≥0.5.23 → onnxruntime==1.22.0 (non-existent on macOS)
```

### Error Message
```bash
pip install crewai==0.148.0
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.22.0 (from crewai) 
(from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0, 1.19.2)
ERROR: No matching distribution found for onnxruntime==1.22.0
```

### Reproduction Evidence
```bash
# Fresh venv on macOS
uv pip install chromadb
# ✅ Installs ChromaDB v1.0.15 with onnxruntime v1.19.2 successfully

uv pip install crewai  
# ❌ Silently downgrades to CrewAI v0.121.0 instead of latest v0.148.0
```

**Key Finding:** ChromaDB itself works perfectly on macOS with onnxruntime 1.19.2, proving CrewAI's requirement for 1.22.0 is artificially high.

### Description
crewai-tools packages are incompatible with stable CrewAI versions due to missing imports.

### Root Cause
crewai-tools v0.47.0+ imports `EnvVar` from `crewai.tools` which doesn't exist in CrewAI v0.121.1.

### Error Message
```python
from crewai_tools import FileReadTool
File "crewai_tools/tools/serper_dev_tool/serper_dev_tool.py", line 8, in <module>
    from crewai.tools import BaseTool, EnvVar
ImportError: cannot import name 'EnvVar' from 'crewai.tools'
```

### Version Compatibility Matrix
| CrewAI Version | crewai-tools Version | Status |
|----------------|---------------------|---------|
| 0.121.1        | 0.45.0             | ✅ Working |
| 0.121.1        | 0.47.0+            | ❌ Broken |
| 0.148.0        | Any                | ❌ Can't install on macOS |

### For macOS Developers
- **Blocked from latest CrewAI features** (6+ months behind)
- **Forced to use outdated versions** with potential security/bug issues
- **Cannot leverage community examples** that use newer API features
- **Development environment fragmentation** across team members

### For Production Deployments
- **No clear upgrade path** without breaking changes
- **Version pinning required** to maintain stability
- **Dependency hell** when integrating with other ML packages
- **Platform-specific deployment complexity**

### For CrewAI Ecosystem
- **Fragmented user base** across incompatible versions
- **Reduced adoption** of newer features
- **Support burden** from version-specific issues
- **Documentation confusion** about which features work where

## Environment Details
```
OS: macOS (Darwin 21.6.0)
Python: 3.12.8
Package Manager: uv/pip
Current Working Combination:
  - CrewAI: 0.121.1
  - crewai-tools: 0.45.0
  - onnxruntime: 1.19.2
```

### 1. Fix onnxruntime Dependency (High Priority)
- **Option A:** Make onnxruntime optional in ChromaDB for CrewAI use cases that don't need embedding models
- **Option B:** Allow onnxruntime version range (>=1.19.0,<1.23.0) instead of pinned version
- **Option C:** Provide CrewAI-lite package without heavy ML dependencies

### 2. Improve Core/Tools Compatibility (Medium Priority)
- **Backward compatibility:** Ensure crewai-tools works with at least 2-3 recent CrewAI versions
- **Version constraints:** Add proper version bounds in crewai-tools dependencies
- **Testing matrix:** CI testing across compatible version combinations

### 3. Better Dependency Management (Long-term)
- **Platform-specific dependencies:** Different requirements for different OS platforms
- **Compatibility matrix documentation:** Clear guidance on which versions work together
- **Dependency resolution testing:** Automated testing of upgrade paths

### 4. Communication Improvements
- **Breaking change announcements:** Clear communication about version compatibility
- **Migration guides:** Step-by-step upgrade instructions
- **Version support policy:** Clear timeline for supporting older versions

## Immediate Workaround
For users encountering this issue, the current working combination is:
```bash
pip install crewai==0.121.1 crewai-tools==0.45.0
```

## Request for CrewAI Team
1. **Prioritize onnxruntime dependency fix** to unblock macOS users
2. **Establish version compatibility policy** between core and tools packages  
3. **Add CI testing** for macOS dependency resolution
4. **Document supported platform/version combinations**

This issue affects a significant portion of the CrewAI user base and blocks adoption of newer features. A fix would immediately unlock access to 6+ months of improvements for macOS developers.

### Root Cause
- CrewAI v0.148.0 requires `onnxruntime==1.22.0` through ChromaDB dependency
- `onnxruntime==1.22.0` does not exist for macOS (only versions up to 1.19.2 are available)
- This creates an unsolvable dependency constraint

### Dependency Chain
```
CrewAI v0.148.0 → ChromaDB ≥0.5.23 → onnxruntime==1.22.0 (non-existent on macOS)
```

### Error Message
```bash
pip install crewai==0.148.0
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.22.0 (from crewai) 
(from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0, 1.19.2)
ERROR: No matching distribution found for onnxruntime==1.22.0
```

### Reproduction Evidence
```bash
# Fresh venv on macOS
uv pip install chromadb
# ✅ Installs ChromaDB v1.0.15 with onnxruntime v1.19.2 successfully

uv pip install crewai  
# ❌ Silently downgrades to CrewAI v0.121.0 instead of latest v0.148.0
```

### Expected behavior

I should be able to run uv pip install --upgrade crewai 'crewai[tools]' and get the latest version.

### Root Cause
- CrewAI v0.148.0 requires `onnxruntime==1.22.0` through ChromaDB dependency
- `onnxruntime==1.22.0` does not exist for macOS (only versions up to 1.19.2 are available)
- This creates an unsolvable dependency constraint

### Dependency Chain
```
CrewAI v0.148.0 → ChromaDB ≥0.5.23 → onnxruntime==1.22.0 (non-existent on macOS)
```

### Error Message
```bash
pip install crewai==0.148.0
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.22.0 (from crewai) 
(from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0, 1.19.2)
ERROR: No matching distribution found for onnxruntime==1.22.0
```

### Reproduction Evidence
```bash
# Fresh venv on macOS
uv pip install chromadb
# ✅ Installs ChromaDB v1.0.15 with onnxruntime v1.19.2 successfully

uv pip install crewai  
# ❌ Silently downgrades to CrewAI v0.121.0 instead of latest v0.148.0
```

### Operating System

Ubuntu 20.04

### Python Version

3.10

### crewAI Version

0.121.0

### crewAI Tools Version

0.45.0

### Virtual Environment

Venv

### Root Cause
- CrewAI v0.148.0 requires `onnxruntime==1.22.0` through ChromaDB dependency
- `onnxruntime==1.22.0` does not exist for macOS (only versions up to 1.19.2 are available)
- This creates an unsolvable dependency constraint

### Dependency Chain
```
CrewAI v0.148.0 → ChromaDB ≥0.5.23 → onnxruntime==1.22.0 (non-existent on macOS)
```

### Error Message
```bash
pip install crewai==0.148.0
ERROR: Could not find a version that satisfies the requirement onnxruntime==1.22.0 (from crewai) 
(from versions: 1.17.0, 1.17.1, 1.17.3, 1.18.0, 1.18.1, 1.19.0, 1.19.2)
ERROR: No matching distribution found for onnxruntime==1.22.0
```

### Reproduction Evidence
```bash
# Fresh venv on macOS
uv pip install chromadb
# ✅ Installs ChromaDB v1.0.15 with onnxruntime v1.19.2 successfully

uv pip install crewai  
# ❌ Silently downgrades to CrewAI v0.121.0 instead of latest v0.148.0
```

### Possible Solution

Resolve your dependency issues

### Additional context

None

**Comment by Vidit-Ostwal** [comment]
This seems very strange to me.
I just installed CrewAI in a new env, in Mac OS Sequoia.

Was able to do it, without any issues.

<img width="583" height="191" alt="Image" src="https://github.com/user-attachments/assets/0cbb48ad-1dcf-44ed-af23-8600a11d1c08" />

**Comment by wanderingnature** [comment]
I am on Intel Mac, are you running Sequoia on Apple or Intel CPU? Although not specific to just onxruntime (this is for onxruntime-genai) there is an issue in onxruntime repo: https://github.com/microsoft/onnxruntime-genai/issues/518

**Comment by Vidit-Ostwal** [comment]
Sequoia

**Comment by wanderingnature** [comment]
Sequoia runs on both Intel and Applie chips. Which do you have?

**Comment by Vidit-Ostwal** [comment]
Apple Chip

Thanks & Regards,
*Vidit Ostwal,*
***@***.*** ***@***.***>*

**Comment by wanderingnature** [comment]
Thanks! The issue is specifically with Intel/Mac
