### ISSUE TITLE
[BUG] Regression in CrewAI 1.9.3: custom BaseTool wrapper around BedrockKBRetrieverTool gets called without args (_run() missing query) and enters infinite tool-use loop

### ISSUE THREAD

**Issue by jonas-cohen-verbit** [crewAIInc/crewAI#4495]
### Description

After upgrading CrewAI from 1.6.1 → 1.9.3, a custom tool wrapper around BedrockKBRetrieverTool no longer receives its required query argument. The tool call fails with:
	•	ParsedBedrockKBRetrieverTool._run() missing 1 required positional argument: 'query'
…and the agent repeatedly attempts to use the tool, effectively entering an infinite tool-calling loop.
In crewai==1.6.1, the same code and workflow work as expected.

The logs also show an events mismatch warning during the loop:
[CrewAIEventsBus] Warning: Event pairing mismatch. 'tool_usage_finished' closed 
'flow_started' (expected 'tool_usage_started')
Tool kb_retrieve executed with result: Error executing tool: ParsedBedrockKBRetrieverTool._run() missing 1 required positional argument: 'query'

This looks like a regression in how tool arguments are passed from the agent → tool execution in newer CrewAI versions.

Environment
	•	crewai==1.9.3 (broken)
	•	crewai==1.6.1 (works)
	•	Tool involved: crewai_tools.aws.bedrock.knowledge_base.retriever_tool.BedrockKBRetrieverTool  ￼
	•	Custom tool extends crewai.tools.BaseTool (wrapper with post-processing)

### Steps to Reproduce

1.	Install and run with crewai==1.9.3
	2.	Create an agent (in a Crew) that has a tool list including a custom wrapper tool around BedrockKBRetrieverTool.
	3.	Ask the agent a question that triggers retrieval from the knowledge base.
	4.	Observe that the tool fails with a missing query arg, and the agent repeatedly retries tool usage.

### Expected behavior

Expected behavior
	•	The tool should be invoked with the query argument (as defined by the tool schema), execute once, and return retrieval results (JSON).

Actual behavior
	•	Tool execution fails because _run() is called without the required query parameter.
	•	The agent loops, repeatedly trying to use the tool.
	•	Event bus warning appears: “Event pairing mismatch … expected tool_usage_started”.

### Screenshots/Code snippets

from typing import Type
import json
from pydantic import BaseModel, Field, PrivateAttr
from crewai.tools import BaseTool
from crewai_tools.aws.bedrock.knowledge_base.retriever_tool import BedrockKBRetrieverTool

class KBQueryInput(BaseModel):
    """Input schema for KB retrieval tool."""
    query: str = Field(..., description="Natural language query for the knowledge base.")

class ParsedBedrockKBRetrieverTool(BaseTool):
    name: str = "kb.retrieve"
    description: str = "Retrieve from Bedrock KB and parse results into RetrievedRef-shaped objects."
    args_schema: Type[BaseModel] = KBQueryInput
    _inner: BedrockKBRetrieverTool = PrivateAttr()

    def __init__(self, inner: BedrockKBRetrieverTool):
        super().__init__()
        self._inner = inner

    def _run(self, query: str) -> str:
        raw = self._inner._run(query)

        try:
            payload = json.loads(raw) if isinstance(raw, str) else raw
        except Exception:
            return json.dumps({"message": "Failed to parse BedrockKBRetrieverTool response as JSON."})

        if not isinstance(payload, dict):
            return json.dumps({"message": "Unexpected BedrockKBRetrieverTool response type."})

        results = payload.get("results")
        if results is None:
            return json.dumps({"message": payload.get("message", "No results found for the given query.")})

        # parsing logic omitted for brevity...
        return json.dumps({"results": results})

def build_kb_retrieval_tool(knowledge_base_id: str, n_results: int = 100) -> BaseTool:
    inner = BedrockKBRetrieverTool(
        knowledge_base_id=knowledge_base_id,
        number_of_results=n_results
    )
    return ParsedBedrockKBRetrieverTool(inner=inner)

### Operating System

Ubuntu 22.04

### Python Version

3.12

### crewAI Version

1.9.3

### crewAI Tools Version

1.9.3

### Virtual Environment

Poetry

### Evidence

[CrewAIEventsBus] Warning: Event pairing mismatch. 'tool_usage_finished' closed 
'flow_started' (expected 'tool_usage_started')
Tool kb_retrieve executed with result: Error executing tool: ParsedBedrockKBRetrieverTool._run() missing 1 required positional argument: 'query'...

### Possible Solution

None
in early version its works

### Additional context

None

**Comment by amabito** [comment]
This feels like a deterministic failure being handled as a transient one.

When the same tool invocation fails with the same argument pattern (e.g., `_run()` missing `query`) and the retry loop treats it generically, it effectively becomes an execution amplifier. The system keeps re-invoking a call that cannot succeed without a state change.

We ran into a similar pattern where argument validation happened inside the retry boundary, so the same broken invocation was replayed repeatedly.

One lightweight mitigation that worked well for us was distinguishing:
- transient failures (network, rate limits, timeouts) → retry
- stable failures (identical input → identical exception) → short-circuit

Even a simple guard such as:
"if the same error signature occurs N times consecutively, halt"
prevented runaway loops without altering the core orchestration logic.

Is the current retry path in crewAI differentiating between transient and deterministic failures, or does everything flow through the same retry handler?

**Comment by jonas-cohen-verbit** [comment]
> This feels like a deterministic failure being handled as a transient one.
> 
> When the same tool invocation fails with the same argument pattern (e.g., `_run()` missing `query`) and the retry loop treats it generically, it effectively becomes an execution amplifier. The system keeps re-invoking a call that cannot succeed without a state change.
> 
> We ran into a similar pattern where argument validation happened inside the retry boundary, so the same broken invocation was replayed repeatedly.
> 
> One lightweight mitigation that worked well for us was distinguishing:
> 
> * transient failures (network, rate limits, timeouts) → retry
> * stable failures (identical input → identical exception) → short-circuit
> 
> Even a simple guard such as: "if the same error signature occurs N times consecutively, halt" prevented runaway loops without altering the core orchestration logic.
> 
> Is the current retry path in crewAI differentiating between transient and deterministic failures, or does everything flow through the same retry handler?

Thank you for the response. I’m not sure what you meant.

What bothered me more is that the exact same code (without any code changes on my end) works properly in crewAI versions lower than 1.9.0 (not including 1.9.0).

**Comment by amabito** [comment]
Totally fair — if the exact same code works on <1.9.0, then this points to a regression rather than just retry behavior.

What I was trying to describe earlier only applies after the failure starts looping — but the first thing to isolate here is what changed in 1.9.x around tool argument binding.

A couple of quick checks that might help narrow it down:

1) Can you share the minimal `_run` / `_arun` signature of your custom BaseTool and how it's registered with the agent?
2) In 1.9.3, does the tool receive any kwargs at all, or is `query` consistently missing?
3) Are you wrapping the tool or relying on signature introspection? If so, 1.9.x may have altered how arguments are constructed before dispatch.

If you can provide a minimal reproducible snippet (even stripped down), it should be possible to pinpoint which change in 1.9.x is breaking argument passing.

**Comment by amabito** [comment]
To clarify: “deterministic vs transient” was just about the *retry loop behavior* — your case still looks like a 1.9.x regression in how tool args are built/passed, and that’s the main thing to isolate first.

**Comment by jonas-cohen-verbit** [comment]
@amabito I shared a snippet of my code above. I will share again:
```python
from __future__ import annotations

import json
from dataclasses import asdict, dataclass
from typing import Any, Optional, Type
from urllib.parse import urlparse

from pydantic import BaseModel, Field, PrivateAttr

from crewai.tools import BaseTool
from crewai_tools.aws.bedrock.knowledge_base.retriever_tool import BedrockKBRetrieverTool

class KBQueryInput(BaseModel):
    """Input schema for KB retrieval tool."""
    query: str = Field(..., description="Natural language query for the knowledge base.")


@dataclass(frozen=True)
class RetrievedRef:
    doc_name: str
    text: str
    score: float
    s3_uri: Optional[str]


def _serialize_retrieved_ref(ref: RetrievedRef) -> dict[str, Any]:
    return asdict(ref)


def _filename_from_uri(uri: Optional[str]) -> str:
    if not uri:
        return "unknown"

    if uri.startswith("s3://"):
        tail = uri.rstrip("/").split("/")[-1]
        return tail or "unknown"

    parsed = urlparse(uri)
    if parsed.path:
        tail = parsed.path.rstrip("/").split("/")[-1]
        return tail or "unknown"

    tail = uri.rstrip("/").split("/")[-1]
    return tail or "unknown"


def _normalize_content_type(result_item: dict[str, Any]) -> str:
    content_type = (
        result_item.get("content_type")
        or result_item.get("contentType")
        or result_item.get("contentType".lower())
        or ""
    )
    return str(content_type).upper()


class ParsedBedrockKBRetrieverTool(BaseTool):
    name: str = "kb.retrieve"
    description: str = "Retrieve from Bedrock KB and parse results into RetrievedRef-shaped objects."
    args_schema: Type[BaseModel] = KBQueryInput
    _inner: BedrockKBRetrieverTool = PrivateAttr()

    def __init__(self, inner: BedrockKBRetrieverTool):
        super().__init__()
        self._inner = inner

    def _run(self, query: str) -> str:
        raw = self._inner._run(query)

        try:
            payload = json.loads(raw) if isinstance(raw, str) else raw
        except Exception:
            return json.dumps({"message": "Failed to parse BedrockKBRetrieverTool response as JSON."})

        if not isinstance(payload, dict):
            return json.dumps({"message": "Unexpected BedrockKBRetrieverTool response type."})

        results = payload.get("results")
        if results is None:
            return json.dumps({"message": payload.get("message", "No results found for the given query.")})

        parsed: list[RetrievedRef] = []
        for item in results or []:
            source_uri = item.get("source_uri") or item.get("sourceUri")
            score = float(item.get("score") or 0.0)
            doc_name = _filename_from_uri(source_uri)

            content_type = _normalize_content_type(item)

            if content_type == "TEXT":
                text = item.get("content", "") or ""
            elif content_type == "IMAGE":
                metadata = item.get("metadata") or {}
                text = metadata.get("x-amz-bedrock-kb-description", "") or ""
            else:
                text = item.get("content", "") or ""

            parsed.append(
                RetrievedRef(
                    doc_name=doc_name,
                    text=text,
                    score=score,
                    s3_uri=source_uri,
                )
            )

        return json.dumps({"results": [_serialize_retrieved_ref(ref) for ref in parsed]})


def build_kb_retrieval_tool(knowledge_base_id: str, n_results: int = 100) -> BaseTool:
    """Build a KB retrieval tool for the given knowledge base ID."""
    inner = BedrockKBRetrieverTool(
        knowledge_base_id=knowledge_base_id,
        number_of_results=n_results
    )
    return ParsedBedrockKBRetrieverTool(inner=inner)

```  

and this is the tool that I give to the agent:
`kb_tool = build_kb_retrieval_tool(knowledge_base_id=knowledge_base_id, n_results=100)`

**Comment by amabito** [comment]
Thanks for sharing the snippet — this helps a lot.

Given that the exact same code works on <1.9.0 and fails on >=1.9.0 with `_run() missing query`, this strongly suggests a regression in how tool arguments are being constructed or bound in 1.9.x rather than a retry issue.

One thing that stands out is the custom `__init__` on a `BaseTool` subclass. Since `BaseTool` is pydantic-based, if initialization changes in 1.9.x affect schema or field registration, the dispatcher might be invoking the tool with empty kwargs — which would explain why `query` is missing.

Two quick experiments that could help isolate it:

1) Modify the constructor to forward model data:
   `def __init__(self, inner: BedrockKBRetrieverTool, **data):`
   `    super().__init__(**data)`
   `    self._inner = inner`

2) Temporarily change `_run` to:
   `def _run(self, query: str = None, **kwargs):`
   and log `kwargs` to see what the dispatcher is actually passing in 1.9.3.

If either restores argument passing, we've likely narrowed the regression to the tool initialization / introspection path introduced in 1.9.x.

**Comment by amabito** [comment]
I've confirmed the root cause of #4495 in source.

## Root Cause (Confirmed)

In 1.9.x Native tool-calling path, crewAI bypasses `CrewStructuredTool.invoke()` and `_parse_args()` entirely and directly calls `BaseTool.run()` via `available_functions`.

### Evidence

**Tool mapping**

`agent_utils.py:94`
```python
available_functions[sanitized_name] = tool.run  # BaseTool.run bound method
```

So Native mode maps directly to `BaseTool.run`, not to `CrewStructuredTool.invoke`.

**Native execution**

`crew_agent_executor.py:856`
```python
tool_func = available_functions[func_name]
raw_result = tool_func(**args_dict)  # no validation
```

`base_tool.py:153`
```python
return self._run(**kwargs)
```

There is no Pydantic validation in this path.

In 1.8.x this path did not exist — tool execution always went through:

```
CrewStructuredTool.invoke()
→ _parse_args()
→ args_schema.model_validate()
```

So missing required arguments were caught as `ValidationError`.

In 1.9.x Native mode:
If `args_dict == {}` (e.g. provider parsing mismatch or empty arguments returned),
Python raises:

```
TypeError: missing required positional argument 'query'
```

This is then fed back to the LLM as a generic failure,
causing deterministic retry loops.

### Minimal Fix Proposal

Add `args_schema` validation inside `_handle_native_tool_calls()` before executing `tool.run`.

Example (conceptual):
```python
original_tool = self._find_original_tool(func_name)
if original_tool and original_tool.args_schema:
    try:
        validated = original_tool.args_schema.model_validate(args_dict)
        args_dict = validated.model_dump()
    except ValidationError as e:
        # Deterministic failure — do not execute tool
        raw_result = f"Argument validation failed: {e}"
        # return or continue without calling tool_func
```

This makes Native behavior consistent with the ReAct path
and prevents deterministic failure loops driven by `TypeError`.

If helpful, I can open a focused PR with:
- minimal validation patch
- regression test for Native tool call with missing required argument

**Comment by amabito** [comment]
I've confirmed the root cause of #4495 in source.

## Root Cause (Confirmed)

In 1.9.x Native tool-calling path, crewAI bypasses `CrewStructuredTool.invoke()` and `_parse_args()` entirely and directly calls `BaseTool.run()` via `available_functions`.

### Evidence

**Tool mapping** — `agent_utils.py:196`

```python
available_functions[sanitized_name] = tool.run  # BaseTool.run bound method
```

So Native mode maps directly to `BaseTool.run`, not to `CrewStructuredTool.invoke`.

**Native execution** — `crew_agent_executor.py:858`

```python
tool_func = available_functions[func_name]
raw_result = tool_func(**args_dict)  # no validation
```

**`base_tool.py:153-158`**

```python
result = self._run(*args, **kwargs)
```

There is no Pydantic validation in this path.

In 1.8.x this path did not exist — tool execution always went through:

```
CrewStructuredTool.invoke() → _parse_args()
```

So missing required arguments were caught as `ValidationError`.

In 1.9.x Native mode, if `args_dict == {}` (e.g. provider parsing mismatch or empty arguments returned):

```
TypeError: missing required positional argument 'query'
```

This is then fed back to the LLM as a generic failure, causing deterministic retry loops.

## Minimal Fix Proposal

Add `args_schema` validation inside `_handle_native_tool_calls()` before executing `tool.run`.

Example (conceptual):

```python
if original_tool and getattr(original_tool, "args_schema", None):
    validated = original_tool.args_schema.model_validate(args_dict)
    args_dict = validated.model_dump()
```

This makes Native behavior consistent with the ReAct path and prevents deterministic failure loops driven by `TypeError`.

If helpful, I can open a focused PR with:
- minimal validation patch
- regression test for Native tool call with missing required argument

**Comment by jonas-cohen-verbit** [comment]
@amabito Thank you again for the response and the help.
I’d be happy to understand, in summary (as simply as possible), what the actual root cause of the problem?
And do you think it’s possible to improve this in the next version (open a PR accordingly, etc.)?

**Comment by amabito** [comment]
Sorry for the delayed reply — I was offline overnight.

Thanks — happy to summarize.

### Root cause (simple)
In **native tool calling mode (1.9.x)**, tool execution can bypass the structured tool validation path and end up calling **`BaseTool.run()` directly** with whatever `args_dict` was parsed from the provider tool-call response.

If the tool-call arguments are **missing / empty** (e.g. `{}` due to a provider response shape edge case or parsing mismatch), there is **no args_schema validation** before calling the tool, so Python raises a raw **`TypeError`** (e.g. missing required `query`). That error is then surfaced back to the model, which can repeat the same call → deterministic retry loop.

### Can we improve it in the next version?
Yes, very likely.

The minimal, low-risk fix is to **validate `args_dict` against the tool’s `args_schema` in the native path** (before executing `tool.run()`), so missing required fields produce a clear **Pydantic `ValidationError`** instead of a raw `TypeError`. That makes native behavior consistent with the structured/ReAct path.

If you’re aligned with that approach, I can open a focused PR with:
- the minimal validation change in the native execution path
- a regression test covering “missing required args” + “valid args still work”

**Comment by jonas-cohen-verbit** [comment]
@amabito thanks again!
If indeed this is the solution, I will be happy if you could open a PR.
that mean that we will see the solution in the next version?

**Comment by amabito** [comment]
Thanks — happy to open a PR 

Yes, if the validation approach is accepted and merged, the fix would be included in the next release after it’s merged to main.

To be precise:

- The change is minimal and only affects the native tool-calling path.
- It makes native mode consistent with the structured/ReAct path by validating `args_dict` against `args_schema` before execution.
- It does not change behavior for valid tool calls.

I’ll open a focused PR shortly with:
- the minimal validation patch
- a regression test covering the missing-required-argument case

Once it’s reviewed and merged, it should naturally ship in the next version.

Let me know if you'd like any adjustments to the approach before I submit it.

**Comment by jonas-cohen-verbit** [comment]
@amabito if you could tag me in the PR / send the link.
So I’ll try to apply the changes locally to make sure the solution actually works for my use case 🙂
Thanks again!

**Comment by amabito** [comment]
Absolutely 👍

I’ll open the PR shortly and tag you so you can test it locally.

It’s a small change limited to the native tool-calling path, so it should be easy to apply and verify on your side.

Once it’s up, feel free to try it with your specific setup — if anything behaves unexpectedly, we can iterate quickly.

Thanks for offering to test it 🙌

**Comment by amabito** [comment]
Thanks! I opened a PR with the minimal native-path args_schema validation + regression tests.

PR: #4507 — https://github.com/crewAIInc/crewAI/pull/4507

Feel free to pull the branch and try it locally — happy to iterate if anything doesn't match your use case.

**Comment by jonas-cohen-verbit** [comment]
> Absolutely 👍
> 
> I’ll open the PR shortly and tag you so you can test it locally.
> 
> It’s a small change limited to the native tool-calling path, so it should be easy to apply and verify on your side.
> 
> Once it’s up, feel free to try it with your specific setup — if anything behaves unexpectedly, we can iterate quickly.
> 
> Thanks for offering to test it 🙌

Hi @amabito ,
I tried to reproduce the bug, but for some reason, without any success (I added Langfuse to my framework, so maybe this affected additional packages as well).

**Comment by amabito** [comment]
Thanks for trying to reproduce it.

A few clarifying questions that might help narrow this down:

1. Is `llm.supports_function_calling()` returning True in your setup?
   (The regression only appears in the native tool-calling path.)

2. When the failure happens, do you see a Python `TypeError`
   (e.g. missing required positional argument), or a `ValidationError`?

3. Can you confirm what `args_dict` looks like right before `tool.run(**args_dict)`?
   In the failing case we observed, it was `{}`.

Langfuse shouldn’t affect argument binding directly, but if it wraps or modifies
the tool call response shape, that could explain why you’re not hitting the same path.

If you can share a minimal reproduction snippet (agent + tool definition),
I can try to reproduce it exactly on my side.

**Comment by amabito** [comment]
To make this concrete, here’s a minimal repro you can copy/paste.

It defines a tool with a required args_schema (x,y), then *forces* a tool call with `{}`.
If args_schema validation is enforced, you should see a Pydantic ValidationError.
If it’s bypassed in native tool-calling, you’ll typically see a TypeError (or the tool is invoked without validation).

--- minimal_repro_crewai_4495.py ---

from __future__ import annotations
import os
from pydantic import BaseModel, Field
from crewai.tools import BaseTool

class AddArgs(BaseModel):
    x: int = Field(...)
    y: int = Field(...)

class AddTool(BaseTool):
    name: str = "add"
    description: str = "Add two integers."
    args_schema = AddArgs
    def _run(self, x: int, y: int) -> int:
        return x + y

from crewai import Agent, Task, Crew
from crewai.llm import LLM

def main():
    llm = LLM(
        model=os.environ.get("CREWAI_REPRO_MODEL", "gpt-4o-mini"),
        temperature=0,
    )
    agent = Agent(
        role="ReproAgent",
        goal="Trigger tool call with missing args to test args_schema validation.",
        backstory="Minimal repro for args_schema validation in native tool calling.",
        llm=llm,
        tools=[AddTool()],
        verbose=True,
    )
    task = Task(
        description=(
            "Use the `add` tool now. Do NOT ask clarification. "
            "Call the tool with an empty JSON object as arguments: {}. "
            "Then return the result."
        ),
        agent=agent,
    )
    print(Crew(agents=[agent], tasks=[task], verbose=True).kickoff())

if __name__ == "__main__":
    main()

--- run ---
export CREWAI_REPRO_MODEL=gpt-4o-mini
python minimal_repro_crewai_4495.py

If you still can’t reproduce, the next best signal is confirming which path is actually executed:
- do you see `_handle_native_tool_calls()` being invoked?

Even a single temporary print at the top of `_handle_native_tool_calls()` would confirm whether we’re discussing the same code path.

(Also: if Langfuse wraps tool-call responses, could you try once with Langfuse disabled to see if the behavior changes?)

**Comment by jonas-cohen-verbit** [comment]
> > Absolutely 👍
> > I’ll open the PR shortly and tag you so you can test it locally.
> > It’s a small change limited to the native tool-calling path, so it should be easy to apply and verify on your side.
> > Once it’s up, feel free to try it with your specific setup — if anything behaves unexpectedly, we can iterate quickly.
> > Thanks for offering to test it 🙌
> 
> Hi [@amabito](https://github.com/amabito) , I tried to reproduce the bug, but for some reason, without any success (I added Langfuse to my framework, so maybe this affected additional packages as well).

@amabito some update:
I moved to an old branch in order to reproduce the error.
I put a breakpoint at [here](https://github.com/crewAIInc/crewAI/blob/63a508f601e5934f7993b0083e59fe90da56bb4f/lib/crewai/src/crewai/agents/crew_agent_executor.py#L844), and I see that `args_dict` there is just an empty dict.

and [your solution](https://github.com/crewAIInc/crewAI/pull/4507/changes#diff-b1043e73ef425a1de56aca007b2b0381a68c53cde384cf4f360bc94ad4764314R864) just make the error different. 

insted of:
```shell
Tool kb_retrieve executed with result: Error executing tool: ParsedBedrockKBRetrieverTool._run() missing 1 required positional argument: 'query'...
╭────────────────────── ✅ Tool Execution Completed (#4) ──────────────────────╮
│                                                                              │
│  Tool Completed                                                              │
│  Tool: kb_retrieve                                                           │
│  Output: Error executing tool: ParsedBedrockKBRetrieverTool._run() missing   │
│  1 required positional argument: 'query'                                     │
│                                                                              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
``` 
now:
```shell
[CrewAIEventsBus] Warning: Ending event 'tool_usage_finished' emitted with empty
scope stack. Missing starting event?
Tool kb_retrieve executed with result: Error executing tool: 1 validation error for KBQueryInput
query
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/mi...
╭─────────────────────── 🔧 Tool Execution Started (#4) ───────────────────────╮
│                                                                              │
│  Tool: kb_retrieve                                                           │
│                                                                              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

╭───────────────────────────── 🔧 Tool Error (#4) ─────────────────────────────╮
│                                                                              │
│  Tool Failed                                                                 │
│  Tool: kb_retrieve                                                           │
│  Iteration: 4                                                                │
│  Error: 1 validation error for KBQueryInput                                  │
│  query                                                                       │
│    Field required [type=missing, input_value={}, input_type=dict]            │
│      For further information visit                                           │
│  https://errors.pydantic.dev/2.11/v/missing                                  │
│                                                                              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯

╭────────────────────── ✅ Tool Execution Completed (#4) ──────────────────────╮
│                                                                              │
│  Tool Completed                                                              │
│  Tool: kb_retrieve                                                           │
│  Output: Error executing tool: 1 validation error for KBQueryInput           │
│  query                                                                       │
│    Field required [type=missing, input_value={}, input_type=dict]            │
│      For further information visit                                           │
│  https://errors.pydantic.dev/2.11/v/missing                                  │
│                                                                              │
│                                                                              │
╰──────────────────────────────────────────────────────────────────────────────╯
```

**Comment by amabito** [comment]
Thanks again for the detailed report and for testing this.

We've identified the root cause — it's at L722:

    func_args = func_info.get("arguments", "{}") or tool_call.get("input", {})

For Bedrock-style tool calls:

{
  "toolUseId": "...",
  "name": "...",
  "input": {...}
}

There is no `function` key, so:

- func_info = tool_call.get("function", {}) → {}
- func_info.get("arguments", "{}") returns the default string "{}"
- "{}" is truthy, so the `or` short-circuits
- tool_call.get("input", {}) is never evaluated
- json.loads("{}") → {}

As a result, the Bedrock `input` is effectively ignored.

The minimal fix is simply to remove the default "{}":

    func_args = func_info.get("arguments") or tool_call.get("input", {})

That allows `None` to fall through properly and Bedrock's `input` to be used.

My PR #4507 improved the error messaging but did not address this underlying logic issue — apologies for that. I'll open a small focused follow-up PR with just this fix.

**Comment by jonas-cohen-verbit** [comment]
> Thanks again for the detailed report and for testing this.
> 
> We've identified the root cause — it's at L722:
> 
> ```
> func_args = func_info.get("arguments", "{}") or tool_call.get("input", {})
> ```
> 
> For Bedrock-style tool calls:
> 
> { "toolUseId": "...", "name": "...", "input": {...} }
> 
> There is no `function` key, so:
> 
> * func_info = tool_call.get("function", {}) → {}
> * func_info.get("arguments", "{}") returns the default string "{}"
> * "{}" is truthy, so the `or` short-circuits
> * tool_call.get("input", {}) is never evaluated
> * json.loads("{}") → {}
> 
> As a result, the Bedrock `input` is effectively ignored.
> 
> The minimal fix is simply to remove the default "{}":
> 
> ```
> func_args = func_info.get("arguments") or tool_call.get("input", {})
> ```
> 
> That allows `None` to fall through properly and Bedrock's `input` to be used.
> 
> My PR [#4507](https://github.com/crewAIInc/crewAI/pull/4507) improved the error messaging but did not address this underlying logic issue — apologies for that. I'll open a small focused follow-up PR with just this fix.

@amabito can you send me the new PR in order totest it?

**Comment by amabito** [comment]
Sure — here's the PR:

https://github.com/crewAIInc/crewAI/pull/4518

It contains only the minimal one-line fix for the L722 short-circuit issue. Let me know if anything looks off while testing.

**Comment by amabito** [comment]
Sure! Here it is: https://github.com/crewAIInc/crewAI/pull/4518

It's a single-line change — just removes the default `"{}"` from `func_info.get("arguments", "{}")` so Bedrock's `input` key can be evaluated properly. Should be straightforward to apply and test on your end.

**Comment by alemarcosa** [comment]
The `query`-missing loop in your issue is a very clean example of why tool schema validation should happen before execution rather than after repeated failure. Once the same malformed call is allowed to keep retrying, the system is paying to repeat a known-bad path. I’ve been following Daedalab because it seems aimed at pre-exec checks, duplicate-action suppression, and retry control, which felt very relevant to what you described.

**Comment by amabito** [comment]
@jonas-cohen-verbit Quick update -- I've rebased #4518 against the latest main to resolve the conflict. The fix is still the same single-line change on L722.

If you get a chance to pull and test on your setup, that would be helpful -- a confirmation from your side would make it easier for maintainers to prioritize the merge.

**Comment by jonas-cohen-verbit** [comment]
> [@jonas-cohen-verbit](https://github.com/jonas-cohen-verbit) Quick update -- I've rebased [#4518](https://github.com/crewAIInc/crewAI/pull/4518) against the latest main to resolve the conflict. The fix is still the same single-line change on L722.
> 
> If you get a chance to pull and test on your setup, that would be helpful -- a confirmation from your side would make it easier for maintainers to prioritize the merge.

@amabito, thanks for the update. I will try to get to that.
Thanks again :)

**Comment by abdullahshahin** [comment]
Drive-by for anyone landing here from search: the `tool_usage_finished` closing `flow_started` pairing warning is the real signal — the agent never emitted `tool_usage_started`, which means the tool-call args extraction failed before `_run` was reached, so `query` arrives as `{}` and the agent retries forever. If the wrapper subclasses `BaseTool` and overrides `__init__`, the `args_schema` class attr can get shadowed by Pydantic field resolution in 1.9.x; declaring `args_schema` on the subclass *and* re-passing it via `super().__init__(args_schema=KBQueryInput)` is usually what restores arg parsing. For the broader "tool re-entered N times with broken args" class, we catch it at the runtime layer instead of leaving it to schema introspection — https://hivein.ai if you're hitting variations elsewhere.
