### PR TITLE
Fixed no session issue while using bedrock

### LINKED ISSUE #2299: [BUG] Amazon Bedrock Embedder Config
### Description

I saw several posts about it but the documentation is not clear on this point. 

When using knowledge, and take the simplest implementation on the CREW level there are my observations for an application that uses AWS exclusively. 

KB is initialized as following: 

```kb_file = "KB.txt"

best_practices_source = TextFileKnowledgeSource(
	file_paths=[
		kb_file,
	]
)
```

1/ When KB is initialized without the embedded config in the CREW class this is the output: `[2025-03-06 19:05:14][WARNING]: Failed to init knowledge: Please provide an OpenAI API key. You can get one at https://platform.openai.com/account/api-keys`
Result: No knowledge is extracted but the flow continues

2/  In case KB is initialized with the embedder config:

```Crew(
			agents=self.agents, 
			tasks=self.tasks, 
			process=Process.sequential,
			verbose=True,
			task_callback=on_task_complete,
			embedder={
				"provider": "bedrock",
				"config": {
					"model": "amazon.titan-embed-text-v2:0",
				}
			},
			knowledge_sources=[
				best_practices_source
			]
		)
```

The response is `[2025-03-06 19:10:29][WARNING]: Failed to init knowledge: 'NoneType' object has no attribute 'client'`

This points me to an issue with the embedder config. However, I can't find information how to properly initialize it as all examples are with Gemini and their API key as parameter. My question is how to debug this and where can I learn more. I would preferably want to use the crewai tools rather than just develop a custom tool. 

For reference if I do knowledge base creation on AWS directly via SDK this is how: 
`self._retrieve_and_generate(bedrock_agent_runtime_client, knowledge_base_id, question)` where the runtime is defined as `bedrock_agent_runtime_client = boto3.client('bedrock-agent-runtime', region_name=region_name)`

I do have access to the models. 

Any guidance is welcome. 

### Steps to Reproduce

See steps 1 and 2 above

### Expected behavior

Ideally to be able to use the embedder or KB with crewai

### Screenshots/Code snippets

as per above

### Operating System

macOS Sonoma

### Python Version

3.10

### crewAI Version

0.102.0

### crewAI Tools Version

0.36.0

### Virtual Environment

Venv

### Evidence

as per above

### Possible Solution

wrong embedder configuration for AWS Bedrock 

### Additional context

none

### PR DESCRIPTION
**Pull request by Vidit-Ostwal**
Fixes #2299

### CODE REVIEW

**Comment by joaomdmoura** [comment]
Disclaimer: This review was made by a crew of AI Agents.

# Code Review for PR #2337 - Improvements in AWS Bedrock Session Handling

## Overview
The changes introduced in PR #2337 significantly enhance the handling of AWS Bedrock session configurations within the embedding configurator. The primary focus revolves around bolstering error handling and optimizing session management practices. Below are insights and recommendations derived from the analysis.

## Key Improvements
1. **Environment Variable Validation**: 
   - The addition of proper checks for required environment variables before creating a session improves robustness and helps prevent runtime errors.
   
2. **Fallback Mechanism**:
   - The implementation of a fallback mechanism for session creation when none is provided enhances the flexibility and reliability of the session management.

3. **Enhanced Error Messaging**:
   - The improved error messages offer clear guidance on what configurations are required, contributing to a better developer experience.

4. **Backward Compatibility**:
   - Maintaining backward compatibility ensures that existing configurations continue to function as expected, which is essential for user transition.

## Specific Code Improvements
Here are specific recommendations for enhancing the code quality further:
  
### Import Organization
**Current:**
```python
import os
import boto3
from typing import Any, Dict, Optional, cast
```
**Recommended:**
```python
from typing import Any, Dict, Optional, cast
import os
import boto3
```
**Reason**: Follow import organization best practices by ordering imports with typing first, then standard library, and third-party packages last for improved readability.

### Constants Definition
**Issue**: Hard-coded environment variable names are scattered in the code.
**Recommendation**:
Define constants at the module level:
```python
REQUIRED_AWS_ENV_VARS = [
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_REGION_NAME"
]
```

### Error Handling Enhancement
Improve error handling with more informative messages:
```python
def _configure_bedrock(config, model_name):
    ...
    if missing_vars:
        raise ConfigurationError(
            f"AWS Bedrock configuration error: Missing environment variables: {', '.join(missing_vars)}.\n"
            f"Please either:\n"
            f"1. Provide a boto3 session in embedding_config\n"
            f"2. Set the required environment variables: {', '.join(REQUIRED_AWS_ENV_VARS)}"
        )
```

### Abstraction of Session Creation
**Recommendation**: Abstract session creation into its own function for cleaner code:
```python
def _create_aws_session_from_env():
    ...
```

### Type Hints
**Recommendation**: Enhance code clarity by adding type hints:
```python
def _configure_bedrock(
    config: Dict[str, Any],
    model_name: Optional[str] = None
) -> AmazonBedrockEmbeddingFunction:
```

## Lessons Learned from Related Discussions
- **Robust Configuration Handling**: Emphasizing the need for thorough validation of configurations prevents potential issues in other parts of the codebase.
- **User-Focused Error Messaging**: By communicating configuration requirements clearly, the developer experience improves significantly, leading to better diagnostics.

## Security and Performance Considerations
- The implementation maintains good security practices by handling sensitive AWS credentials through environment variables without hardcoding them. Performance overhead is minimal as session creation occurs only once, enhancing application responsiveness.

## Testing Recommendations
To ensure the stability and reliability of these changes:
1. Implement unit tests for missing environment variable scenarios.
2. Add integration tests to confirm successful session creation.
3. Utilize mocks in tests for isolating AWS session creation.

## Documentation Suggestions
Augment the `_configure_bedrock` method with a detailed docstring to clarify its purpose, parameters, and return values.

In summary, while this PR marks a significant improvement in the management of AWS Bedrock sessions, implementing the above recommendations can further enhance code maintainability and usability. The focus on robust error handling, user-friendly messaging, and adherence to best practices illustrates a strong commitment to quality software development.

**Comment by Vidit-Ostwal** [comment]
@lucasgomide, should I close this PR?

I think the time it was raised the documentation for this was not there, and user was expecting the boto3 session to be created by just giving the env variable?

Now the documentation states to create a session and pass it directly, let me know on this 
https://docs.crewai.com/concepts/memory#using-amazon-bedrock-embeddings
