### ISSUE TITLE
Cannot Register Custom Tools with Agents in CrewAI 0.150.0 – No Supported Pattern Works

### ISSUE THREAD

**Issue by PVoola** [crewAIInc/crewAI#3226]
### Description

Hi CrewAI Team,

I’m using CrewAI version 0.150.0 and attempting to build real-world agents that use custom tools for integrating external APIs (e.g., fetching logs from New Relic).
However, every custom tool pattern (function, dict, class, decorator, BaseTool) fails with either Pydantic validation errors or abstract method errors, depending on approach.

What is the currently supported and recommended method for adding custom, user-defined tools to an Agent in CrewAI 0.150.0?

If none is supported, is there an ETA for this functionality to return or a version I should use instead?

### Steps to Reproduce

What I Tried:

    Function Tool:

def fetch_logs():
    # ... API code here (uses env vars, no secrets in code)

from crewai import Agent
fetcher = Agent(
    role='CrashFetcher',
    goal='Extract logs',
    tools=[fetch_logs],
    allow_delegation=False
)

Error:

pydantic_core._pydantic_core.ValidationError: 1 validation error for Agent
tools.0
  Input should be a valid dictionary or instance of BaseTool [type=model_type, input_value=<function fetch_logs at ...>, input_type=function]

Dict Tool:

fetch_logs_tool = {
    "name": "fetch_logs",
    "description": "Fetches logs.",
    "function": fetch_logs
}
fetcher = Agent(
    ...,
    tools=[fetch_logs_tool],
    ...
)

Error:
(Similar validation failure)

Class Tool with BaseTool:

from crewai_tools import BaseTool

class FetchLogsTool(BaseTool):
    name = "fetch_logs"
    description = "Fetches logs."
    def _run(self):
        # ...
        pass
fetcher = Agent(
    ...,
    tools=[FetchLogsTool()],
    ...
)

Error:

    ImportError: cannot import name 'BaseTool' from 'crewai_tools' ...

    Decorator (@tool) Pattern:

        Not available in this version.

### Expected behavior

Expected Behavior:
I should be able to register and use my own custom tools (either as a class, function, or with a decorator) so my agents can interact with external APIs, in line with CrewAI’s vision and documentation.

Actual Behavior:
No approach for registering custom tools works in CrewAI 0.150.0. Only built-in tools appear to work. All custom patterns fail with validation or import errors.

### Screenshots/Code snippets

def fetch_logs():
    # ...fetch from API...

from crewai import Agent
fetcher = Agent(
    role='CrashFetcher',
    goal='Extract logs',
    tools=[fetch_logs],  # or dict or class, same result
    allow_delegation=False
)
# Error on agent initialization

### Operating System

Other (specify in additional context)

### Python Version

3.12

### crewAI Version

crewai version: 0.150.0

### crewAI Tools Version

Version: 0.58.0

### Virtual Environment

Venv

### Evidence

Logs/Error Output:

Traceback (most recent call last):
  File "/Users/xx/Documents/Development/github/crash-agent-prototype/crew.py", line 14, in <module>
    fetcher = Agent(
              ^^^^^^
  File "/Users/xx/Documents/Development/github/crash-agent-prototype/.venv/lib/python3.12/site-packages/pydantic/main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Can't instantiate abstract class BaseTool without an implementation for abstract method '_run'

### Possible Solution

None

### Additional context

“We want to integrate CrewAI with real-world business systems and believe custom tools are essential for enterprise use.”

**Comment by lucasgomide** [comment]
Have you take a look [here](https://docs.crewai.com/en/learn/create-custom-tools#create-custom-tools)?

Here is an example of Tool as a function using @tool decorator

```python
from crewai.tools import tool

@tool("Tool Name")
def my_simple_tool(question: str) -> str:
    """Tool description for clarity."""
    # Tool logic here
    return "Tool output"
```

Using BaseTool class

```python
from typing import Type
from crewai.tools import BaseTool
from pydantic import BaseModel, Field

class MyToolInput(BaseModel):
    """Input schema for MyCustomTool."""
    argument: str = Field(..., description="Description of the argument.")

class MyCustomTool(BaseTool):
    name: str = "Name of my tool"
    description: str = "What this tool does. It's vital for effective utilization."
    args_schema: Type[BaseModel] = MyToolInput

    def _run(self, argument: str) -> str:
        # Your tool's logic here
        return "Tool's result"
```
